### ISSUE TITLE
The Rod Lacks a Common Tier&Weights don't Work

### ISSUE THREAD

**Issue by CCCClear** [Stereowalker/Reforged#40]
In the latest forge version of 1.18.2, you will only get lucky fishing rods for crafting or reforging. I tried to add it to the common tool, but it didn't work.
The weight system doesn't work (just sense), and the high weight doesn't significantly increase the occurrence probability of a tier. I think we should strengthen the occurrence probability of common to make the whole mod more balanced.
And the fact that currently tools and weapons don't have a completely negative tier makes the whole mod incomplete. Of course, I can add them myself, but means it's hard for players who aren't the authors of the modpack to use.
I hope my feedback will be useful to the development of the whole mod.

**Comment by Stereowalker** [comment]
If you want the lucky tier to appear less often, you should reduce the weight of the lucky tier.

The "weight" system takes into account every possible tier an item can get and gets their weights. Theoretically, since you added the fishing rod to the common tier, the total weight would bump from 3 to 11. A random number is generated between 0 and 10 and if it lands between 0 and 2, you get the lucky tier as it has a weight of 3. One of 3 things must have happened in your case. (1) you were lucky and kept rolling 0,1,2 or (2) there is something fundamentally flawed with the way the item picker is picking the the fishing rod as it's the only one using an "id" while the others use "tag", or (3) you used a "tag" for the fishing rod "verifier" rather than an "id".

Lastly, you are indeed right about a lack of negative tiers for tools. I haven't really gotten around to working on that as I was busy coming up with tiers for bows. But you should be able to simply create a datapack and distribute it. I'm fairly certain that java players know how to use them given how more commonplace they are now. 

Thanks for the feedback. It was a real eye opener.
